[build]
# Configuration for these lints should be placed in `.clippy.toml` at the crate root.
rustflags = ["-Dwarnings"]

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-args=-z stack-size=268435456",
]