
const N_ROWS: u32 = 256;
const N_EXTENDED_ROWS: u32 = N_ROWS * 4;
const N_STATE: u32 = 16;
const N_INSTANCES_PER_ROW: u32 = 8;
const N_COLUMNS: u32 = N_INSTANCES_PER_ROW * N_COLUMNS_PER_REP;
const N_HALF_FULL_ROUNDS: u32 = 4;
const FULL_ROUNDS: u32 = 2u * N_HALF_FULL_ROUNDS;
const N_PARTIAL_ROUNDS: u32 = 14;
const N_LANES: u32 = 16;
const N_COLUMNS_PER_REP: u32 = N_STATE * (1 + FULL_ROUNDS) + N_PARTIAL_ROUNDS;
const GEN_TRACE_WORKGROUP_SIZE: u32 = N_ROWS * N_LANES / GEN_TRACE_THREADS_PER_WORKGROUP;
const GEN_TRACE_THREADS_PER_WORKGROUP: u32 = 256;
const INTERPOLATE_WORKGROUP_SIZE: u32 = 8;
const INTERPOLATE_THREADS_PER_WORKGROUP: u32 = 256;

const N_ORIGINAL_COLUMN_SIZE: u32 = N_LANES * N_ROWS;

const SECURE_EXTENSION_DEGREE: u32 = 4;
const N_INTERACTION_COLUMNS: u32 = N_INSTANCES_PER_ROW * SECURE_EXTENSION_DEGREE;
// const GEN_INTERACTION_TRACE_WORKGROUP_SIZE: u32 = N_ROWS * N_LANES / GEN_INTERACTION_TRACE_THREADS_PER_WORKGROUP;
const GEN_INTERACTION_TRACE_THREADS_PER_WORKGROUP: u32 = 256;

const N_LINE_TWIDDLES_SIZE: u32 = N_EXTENDED_ROWS * N_LANES;
const N_LINE_TWIDDLES_FLAT_SIZE: u32 = N_LINE_TWIDDLES_SIZE * 2;
const N_CIRCLE_TWIDDLES_SIZE: u32 = N_LINE_TWIDDLES_SIZE * 2;
// PADDING
const N_ORIGINAL_TRACE_COLUMNS: u32 = 1 + N_COLUMNS + N_INTERACTION_COLUMNS + 3;
const N_PREPROCESSED_COLUMNS: u32 = 1;

const N_FLAT_MAX_ARRAY_SIZE: u32 = N_ORIGINAL_COLUMN_SIZE * N_COLUMNS;